site_name: "tangy"
site_author: Peter Barrow

repo_name: PeterBarrow/tangy
repo_url: https://github.com/Peter-Barrow/tangy

copyright: Copyright © 2024 Peter Thomas Barrow

theme:
  name: "material"
  language: en
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant

  font:
    text: IBM Plex Sans
    code: IBM Plex Mono

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [tangy/*]
          options:
          # docstring_style: google
            allow_inspection: true
            docstring_section_style: table
            merge_init_into_class: true
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_category_heading: true
            summary: true
  - mkdocs-jupyter

nav:
  - "Home": index.md
  - "API Reference": api.md
  # - "Guided Tour": guided_tour.ipynb
  - "License": license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Peter-Barrow/tangy
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tangy/
