[tool.poetry]
name = "tangy"
version = "0.1.1"
description = "A library to manage timetags"
authors = ["Peter Thomas Barrow <peter.barrow.93@gmail.com>"]
readme = "README.md"
exclude = [
    "tangy/_ext/*",
    "tangy/_ext/src/*",
    "tangy/_ext/*.html"
    ]
include = [
    "tangy/*.a",
    "tangy/*.so",
    "tangy/*.dll",
    "tangy/*.lib",
]

[tool.poetry.dependencies]
python = "^3.9"
setuptools = "^69.1.1"
cython = "^3.0.9"
numpy = "^1.26.4"
pytkdocs = "^0.16.1"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocs-material = "^8.5.10"
mkdocstrings = "^0.23.0"
mkdoxy = "^1.1.7"

[build-system]
requires = ["poetry-core", "setuptools", "Cython", "numpy"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
generate-setup-file = false
script = "setup.py"
