[tool.poetry]
name = "tangy"
version = "0.1.0"
description = "A library to manage timetags"
authors = ["Peter Thomas Barrow <peter.barrow.93@gmail.com>"]
readme = "README.md"
exclude = [
    "tangy/_ext/*",
    "tangy/_ext/src/*",
    "tangy/_ext/*.html"
    ]

[tool.poetry.dependencies]
python = "^3.9"
setuptools = "^69.1.1"
cython = "^3.0.9"
numpy = "^1.26.4"

[build-system]
requires = ["poetry-core", "setuptools", "Cython", "numpy"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
generate-setup-file = false
script = "setup.py"
